version: '3.8'
services:
  postgres:
    build:
     context: .
     dockerfile: Dockerfile
    image: health-tracker-postgres-prod
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${VOLUME_PATH}:/var/lib/postgresql/data
